steps:
  build:
    image: node:24
    commands:
      - npm ci
      - npm run build

  deploy:
    image: docker:27-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - mkdir -p /srv/apps/tourin-web-landing
      - cd /srv/apps/tourin-web-landing
      - git pull origin main || true
      - docker compose down
      - docker compose up -d --build
