steps:
  build:
    image: docker:27
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t tourin-web-landing:latest .
      - mkdir -p /srv/apps/tourin-web-landing
      - cd /srv/apps/tourin-web-landing
      - |
        cat <<'EOF' > docker-compose.yml
        services:
          app:
            image: tourin-web-landing:latest
            container_name: tourin-web-landing
            restart: always
            networks:
              - proxy
            expose:
              - "80"
            healthcheck:
              test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 10s
          networks:
            proxy:
              external: true
          EOF
      - docker compose -f docker-compose.yml down || true
      - docker compose -f docker-compose.yml up -d
