services:
  tourin-web-landing:
    container_name: tourin-web-landing
    build: .
    restart: always
    ports:
      - "3001:80"
    networks:
      - proxy

networks:
  proxy:
    external: true
